// modules
import Head from 'next/head'
import { useEffect, useState } from 'react'
import Link from 'next/link'
import { Passage } from '@passageidentity/passage-js'

// project files
import { env } from '../env/server.mjs'
import Banner from '../components/Banner'

// types
import type { GetStaticProps, InferGetStaticPropsType, NextPage } from 'next'

const Content: React.FC<{
  appID: string
}> = ({ appID }) => {
  const [username, setUsername] = useState<string>()
  const [authState, setAuthState] = useState<boolean>()
  const passage = new Passage(appID)

  const logout = () => {
    passage.signOut()
    setAuthState(false)
  }

  useEffect(() => {
    if (username == null) {
      passage
        .getCurrentUser()
        .userInfo()
        .then((info) => {
          if (info == null || info.email == null || info.phone == null) {
            logout()
            return
          }

          setAuthState(true)
          setUsername(info?.email == null ? info?.phone : info.email)
        })
    }
  }, [username])

  if (authState == null) return <div>Loading...</div>
  if (!authState) return <passage-auth app-id={appID} />

  return (
    <div className='container mx-auto w-1/3 flex flex-col items-stretch p-8'>
      <h2 className='text-2xl'>Welcome back</h2>
      <p>{username}</p>
      <Link href='/dashboard'>
        <button
          type='button'
          className='p-2 mt-4 mb-1 bg-blue-600 hover:bg-blue-500 focus:bg-blue-500 rounded-md'
        >
          Go to Dashboard
        </button>
      </Link>
      <div className='flex grow flex-row justify-between'>
        <span>Not you?</span>
        <button type='button' onClick={logout} className='underline'>
          Log out
        </button>
      </div>
    </div>
  )
}

const Home: NextPage = ({
  appId,
}: InferGetStaticPropsType<typeof getStaticProps>) => {
  useEffect(() => {
    require('@passageidentity/passage-elements/passage-auth')
  }, [])

  return (
    <>
      <Head>
        <title>Passage Demo</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='w-screen h-screen overscroll-none bg-neutral-800 text-white'>
        <Banner />
        <Content appID={appId} />
      </main>
    </>
  )
}

export default Home

export const getStaticProps: GetStaticProps = async (context) => {
  return {
    props: {
      appId: env.PASSAGE_APP_ID,
    },
  }
}
